text = """
Uma das principais características da teologia adventista é a interpretação historicista das profecias apocalípticas das Escrituras fundamentada no assim chamado princípio dia-ano de interpretação profética.2 Baseado na ideia de que cada dia profético representa um ano literal, as 70 semanas de Daniel 9:24-27 devem ser vistas como sendo 490 anos; os 1.260 dias de Apocalipse 11:3 e 12:6 (ver também Dn 7:25; 12:7; Ap 11:2; 12:14; 13:5), como sendo 1.260 anos; os 1.290 dias de Daniel 12:11, como sendo 1.290 anos; os 1.335 dias de Daniel 12:12, como sendo 1.335 anos; e as 2.300 “tardes e manhãs” de Daniel 8:14,3 como sendo 2.300 anos.

Tradicionalmente, os adventistas do sétimo dia apontam o ano 508 d.C. como sendo o início dos 1.290 e dos 1.335 anos, e, 30 anos depois, o ano 538 d.C. como sendo o início dos 1.260 anos.4 A principal data de referência para esses cálculos tem sido o ano de 1798 d.C., quando o papa Pio VI foi capturado e aprisionado na França, vindo a morrer no exílio.5 Subtraindo os 1.260 anos de 1798, os intérpretes adventistas chegaram até o ano de 538. Tirando 1.290 anos de 1798, eles chegaram ao ano de 508. Enquanto que os 1.290 e os 1.260 anos tiveram seu término no mesmo ano de 1798, os 1.335 anos são contados como terminando 45 anos depois, entre 1843-1844 (veja o diagrama abaixo).

Embora a data de 1798 esteja bem estabelecida pelo importante evento que foi o aprisionamento do papa, o significado de 508 e 538 tem sido questionado por diversos intérpretes críticos que consideram essas datas como destituídas de um sentido histórico mais relevante.6 Mas, se vistas dentro do amplo contexto de estabelecimento da supremacia papal, as datas tomam sentido como importantes expressões desse processo.

Entre os estudos mais relevantes das fontes históricas que sustentam essas datas figuram os de Uriah Smith, intitulado The Prophecies of Daniel and the Revelation (1944),7 e a dissertação de mestrado de C. Mervyn Maxwell, sob o título “An Exegetical and Historical Examination of the Beginning and Ending of the 1260 Days of Prophecy with Special Attention Given to A.D. 538 and 1798 as Initial and Terminal Dates” (1951).8 Mas parece evidente que essas investigações poderiam ser ampliadas, levando-se em consideração uma perspectiva histórica mais ampla.
"""
